import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import { createRequire } from "node:module";

// eslint-config-next sets `settings.react.version = "detect"`, and detection is
// the only path that calls `context.getFilename()`, which ESLint 10 removed.
// Pinning the installed version (read, never hard-coded) skips detection.
const reactVersion = createRequire(import.meta.url)("react/package.json").version;

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  { settings: { react: { version: reactVersion } } },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage` (S0.6, #81) — not source.
    "coverage/**",
  ]),
]);

export default eslintConfig;
