#!/usr/bin/env bash
# Issue and wire a TLS certificate for one product's marketing_domain (S0.5, #80). Run as root
# ON THE VPS, after the domain's DNS A record points here and `setup_site` has generated its vhost:
#
#   infra/deploy/enable-tls.sh acme.example
#
# Idempotent: re-running with a live certificate re-writes the snippet and reloads, but does not
# ask Let's Encrypt for a new cert (their rate limits are per-domain-per-week and unforgiving).
set -euo pipefail

DOMAIN="${1:-}"
[ -n "$DOMAIN" ] || { echo "usage: enable-tls.sh <domain>" >&2; exit 1; }
[ "$(id -u)" -eq 0 ] || { echo "enable-tls: must run as root" >&2; exit 1; }

ACME_WEBROOT=/var/www/acme
TLS_SNIPPET_DIR="/etc/nginx/snippets/sme-tls/$DOMAIN"
LIVE_DIR="/etc/letsencrypt/live/$DOMAIN"
ENV_FILE=/etc/sme/sme.env
[ -f "$ENV_FILE" ] && { set -a; . "$ENV_FILE"; set +a; }

say() { printf '\n== %s\n' "$1"; }

say "preflight"
# The vhost must already exist, because certbot validates over HTTP against it — and that vhost is
# what carries the ACME include. Issuing before `setup_site` has run would fail with a timeout and
# burn a rate-limit slot.
VHOST="${SME_NGINX_SITES_ROOT:-/etc/nginx/sites-enabled}/$DOMAIN.conf"
[ -f "$VHOST" ] || { echo "enable-tls: $VHOST not found — run setup_site for this product first" >&2; exit 1; }
grep -q 'sme-acme.conf' "$VHOST" || {
    echo "enable-tls: $VHOST does not include sme-acme.conf." >&2
    echo "  Without it the dotfile deny added in #78 blocks /.well-known/acme-challenge/ and" >&2
    echo "  validation will time out with nothing in the app logs. Redeploy the site first." >&2
    exit 1
}
install -d -o root -g www-data -m 755 "$ACME_WEBROOT/.well-known/acme-challenge"

say "challenge path reachable?"
# Prove the challenge path works BEFORE asking Let's Encrypt, so a misconfiguration costs a local
# 404 instead of a failed validation against the rate limit. This is the exact check that would
# have caught the #78 dotfile-deny trap.
PROBE="sme-preflight-$$"
echo "$PROBE" > "$ACME_WEBROOT/.well-known/acme-challenge/$PROBE"
PROBE_OK=0
if curl -fsS --max-time 5 -H "Host: $DOMAIN" \
    "http://127.0.0.1/.well-known/acme-challenge/$PROBE" 2>/dev/null | grep -qx "$PROBE"; then
    PROBE_OK=1
fi
rm -f "$ACME_WEBROOT/.well-known/acme-challenge/$PROBE"
[ "$PROBE_OK" -eq 1 ] || {
    echo "enable-tls: the ACME challenge path is NOT served for $DOMAIN — refusing to call certbot." >&2
    echo "  Check that $VHOST includes sme-acme.conf and that nginx has been reloaded." >&2
    exit 1
}
echo "challenge path serves correctly"

say "certificate"
if [ -d "$LIVE_DIR" ] && openssl x509 -checkend 2592000 -noout -in "$LIVE_DIR/fullchain.pem" >/dev/null 2>&1; then
    echo "live certificate for $DOMAIN is valid for >30 more days — not reissuing"
else
    # --webroot, not --nginx: the nginx plugin edits the vhost in place, and `deploy_site`
    # regenerates that file on every setup_site run, so the plugin's edits would be silently
    # erased and the site would fall back to HTTP with a valid cert nobody serves.
    certbot certonly --webroot -w "$ACME_WEBROOT" -d "$DOMAIN" \
        --non-interactive --agree-tos --keep-until-expiring \
        --deploy-hook /usr/local/sbin/sme-nginx-reload
fi

say "tls snippet"
# Written OUTSIDE the generated vhost, into a directory the vhost pulls in with a WILDCARD
# include. Wildcards are what make this survive regeneration: `include .../*.conf` is legal when
# it matches nothing (so a domain without TLS still loads), and the generated vhost never has to
# know whether a certificate exists.
install -d -m 755 "$TLS_SNIPPET_DIR"
cat > "$TLS_SNIPPET_DIR/tls.conf" <<EOF
# Generated by enable-tls.sh for $DOMAIN — do not edit; re-run the script.
# Included by the generated vhost via: include /etc/nginx/snippets/sme-tls/$DOMAIN/*.conf;
listen 443 ssl;
listen [::]:443 ssl;
ssl_certificate     $LIVE_DIR/fullchain.pem;
ssl_certificate_key $LIVE_DIR/privkey.pem;
include /etc/letsencrypt/options-ssl-nginx.conf;
ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
EOF
chmod 644 "$TLS_SNIPPET_DIR/tls.conf"

say "reload"
/usr/local/sbin/sme-nginx-reload

cat <<EOF

TLS enabled for $DOMAIN.

Renewal is automatic: certbot.timer is already active on this box and the --deploy-hook above
reloads nginx after each renewal. Check it with:

  systemctl list-timers | grep certbot
  certbot certificates

Remember to set SME_PUBLIC_API_BASE_URL / SME_OAUTH_REDIRECT_BASE_URL to the https origin in
$ENV_FILE and redeploy — generated landing sites bake the API origin into their funnel JS.
EOF
